version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /PAXminer
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /weaselbot
    schedule:
      interval: weekly
