version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: test
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: docker
    directory: /PAXminer
    target-branch: test
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: docker
    directory: /weaselbot
    target-branch: test
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: pip
    directory: /PAXminer
    target-branch: test
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: pip
    directory: /PAXminer/database_management
    target-branch: test
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: pip
    directory: /weaselbot
    target-branch: test
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: pip
    directory: /slackblast/slackblast
    target-branch: test
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: pip
    directory: /qsignups/qsignups
    target-branch: test
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: pip
    directory: /qsignups/weinkes
    target-branch: test
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: pip
    directory: /migration
    target-branch: test
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
