FROM public.ecr.aws/lambda/python:3.14

WORKDIR ${LAMBDA_TASK_ROOT}

COPY PAXminer/requirements-slack.txt requirements-slack.txt
RUN pip install --no-cache-dir -r requirements-slack.txt

COPY PAXminer/slack_app.py ./
COPY PAXminer/slack_schedule.py ./
COPY PAXminer/config_paxminer.py ./
COPY PAXminer/config_schedule.py ./
COPY PAXminer/scheduling.py ./
COPY PAXminer/report_defaults.json ./
COPY PAXminer/achievement_defaults.json ./
COPY PAXminer/schedule_schema.py ./
COPY PAXminer/slack_util.py ./
COPY PAXminer/slack_http.py ./
COPY PAXminer/slack_blocks.py ./
COPY PAXminer/paxminer_db.py ./
COPY PAXminer/common/ ./common/
COPY PAXminer/achievements/__init__.py ./achievements/__init__.py
COPY PAXminer/achievements/activity.py ./achievements/activity.py
COPY PAXminer/achievements/versions.py ./achievements/versions.py
COPY PAXminer/achievements/range.py ./achievements/range.py
COPY PAXminer/achievements/copy.py ./achievements/copy.py
COPY PAXminer/achievements/emoji.py ./achievements/emoji.py

CMD ["slack_app.handler"]
